#=================================================
# https://github.com/janboo/docker-smartdns
# Description: Build smartdns docker using GitHub Actions
# Lisence: MIT
# Author: Janboo
#=================================================

name: Docker Image for smartdns

on:
  push:
    branches: [ master ]
#  schedule:
#    - cron: '0 10 * * *'
#  pull_request:
#    branches: [ master ]

env:
  REPO_NAME: docker-smartdns
  REPO_VER: r46

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare Tags Name
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME
          VERSION=$REPO_VER
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{ steps.prep.outputs.tags }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
